# Generated by Django 4.2 on 2025-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='type',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], default='backend', max_length=10),
        ),
    ]
