# Generated by Django 4.2 on 2025-05-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Years of development experience', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, help_text='Primary area of technical expertise', max_length=100, null=True),
        ),
    ]
