# Generated by Django 4.2 on 2025-03-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_framework_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], default='Backend', max_length=10),
        ),
    ]
