# Generated by Django 4.2 on 2025-03-20 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_project_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='field',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='field',
            name='default_value',
        ),
        migrations.RemoveField(
            model_name='field',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='field',
            name='max_length',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], max_length=10),
        ),
    ]
