# Generated by Django 4.2 on 2025-03-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_field_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
    ]
