# Generated by Django 4.2 on 2025-03-27 10:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_field_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='script_file',
            field=models.FileField(blank=True, help_text='Upload a script file for project creation', null=True, upload_to=api.models.project_script_upload_path),
        ),
    ]
