# Generated by Django 4.2 on 2025-04-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_project_script_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to='frameworks/scripts/'),
        ),
    ]
