# Generated by Django 4.2 on 2025-04-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_framework_script_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework',
            name='script_file',
        ),
    ]
