# Generated by Django 4.2 on 2025-04-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_framework_script_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exemple',
        ),
    ]
