# Generated by Django 4.2 on 2025-04-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_exemple'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zips/'),
        ),
    ]
