# Generated by Django 4.2 on 2025-04-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_zip_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='model_name',
        ),
        migrations.AddField(
            model_name='project',
            name='selected_tables',
            field=models.JSONField(default=list),
        ),
    ]
