# Generated by Django 4.2 on 2025-04-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_project_model_name_project_selected_tables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='selected_tables',
            new_name='tables',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
